### ISSUE TITLE
Using this package with react-hot-toast

### ISSUE THREAD

**Issue by hawkyre** [jamiebuilds/tailwindcss-animate#11]
I am trying to use this package with `react-hot-toast` but the final state doesn't persist after the animation ends. If I use the `fade-out` class, the opacity just goes back to 100% when the animation ends. I wonder if there's something I could do to persist the final animation state.

This is the code that I'm using to build the custom toast:

```tsx
return toast.custom((t) => (
    <>
      <div
        className={`${
          t.visible
            ? 'animate-in fade-in slide-in-from-top'
            : 'animate-out fade-out'
        } pointer-events-auto transition`}
      >
        <SuccessAlert message={text} />
      </div>
    </>
  ));
```

`react-hot-toast` deletes the toast 1 second after marked as visible when using the custom builder, so if the animation is shorter it kinda breaks.

I'd like to find a solution that doesn't involve altering the duration of either animation if possible.

**Comment by jamiebuilds** [comment]
You may just want to set the `animation-fill-mode` to `both` using `fill-mode-both`

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode

**Comment by clearly-outsane** [comment]
That was it thank you very much
