### ISSUE TITLE
don't animate until element comes into view

### ISSUE THREAD

**Issue by pguardiario** [jamiebuilds/tailwindcss-animate#29]
What's the best way to do this? I want the animation to happen when they scroll it into view

**Comment by pedroapfilho** [comment]
What's your setup? Are you using `Next.js`?

**Comment by robtherobot12** [comment]
I would like to do this too - my setup is next.js.

**Comment by jamiebuilds** [comment]
Until CSS has [scroll driven animations](https://w3c.github.io/csswg-drafts/scroll-animations/) (Work in progress, not supported by any browser), animating on scroll will require JavaScript code.

I'm not going to require JavaScript for this library, so I suggest that you look for other JavaScript libraries for now if you want to do this.
