### ISSUE TITLE
`animate-in` and `animate-out` on 1 class

### ISSUE THREAD

**Issue by m10rten** [jamiebuilds/tailwindcss-animate#34]
Hi, was wondering if this is possible, lets say we have a dialog or drawer that opens with animate-in, but now i want to close it using the exit state and with animate-out but that is not possible.

**Comment by m10rten** [comment]
tried that, `cn("animate-in", "animate-out")` or something like this, does not work, my guess is because in and out do not work alongside eachother.

**Comment by Elbasel** [comment]
yes, they both override the animation-name css.
so you need to handle them using javascript.

**Comment by fzsf163** [comment]
> yes, they both override the animation-name css. so you need to handle them using javascript.

May I please have an example code. I have never done it before.
