### ISSUE TITLE
Release the `index.d.ts` file

### ISSUE THREAD

**Issue by A7med3bdulBaset** [jamiebuilds/tailwindcss-animate#44]
two months ago, You added an `index.d.ts` but seems like it's not been released to `npm` yet. I want to use this in the `tailwind.config.ts` file but I get an error because there is no declaration file. I double-checked [npm](https://www.npmjs.com/package/tailwindcss-animate) and the `node_modules` there is no this file:
https://github.com/jamiebuilds/tailwindcss-animate/blob/cb49af9493e666b905717d4e6aa40e2e69285517/index.d.ts#L1-L3

**Comment by jamiebuilds** [comment]
Published
