### ISSUE TITLE
Cannot find declaration file

### ISSUE THREAD

**Issue by ernstoarllano** [jamiebuilds/tailwindcss-animate#45]
Installed `tailwindcss-animate` into a workspace and keep getting an error. I tried adding a `global.d.ts` file with `declare module 'tailwindcss-animate'`, but nothing seems to work. Any ideas on how to fix this?

<img width="1435" alt="Screenshot 2023-08-25 at 11 28 03 AM" src="https://github.com/jamiebuilds/tailwindcss-animate/assets/5606227/deac5474-18d0-4e1e-bf10-e4050ff371a5">

**Comment by jamiebuilds** [comment]
Published new version
