### ISSUE TITLE
animate-out is not working

### ISSUE THREAD

**Issue by ansarizafar** [jamiebuilds/tailwindcss-animate#9]
I am using this plugin in a solidjs app but it seems animate-out is not working with animate-in on the same element.  Is it not possible to use animate-in/out on the same element?

**Comment by jamiebuilds** [comment]
You can use them on the same element, just not at the same time. You'll need to apply the `animate-out` class when you want the animation to happen.

[React](http://reactcommunity.org/react-transition-group/transition) and [Vue](https://vuejs.org/guide/built-ins/transition.html#css-based-transitions) both have `<Transition/>` components that can help with this.

**Comment by ansarizafar** [comment]
Its working now with solid-transition-group package. Thanks
